- deployment/docker-compose.override.template.yml
Removed the empty lines to make local deployment straightforward
> Removed empty lines in docker-compose.override.template.yml

- deployment/.template.env
- deployment/docker-compose.override.devcontainer.yml
- deployment/docker-compose.override.template.yml
- deployment/docker-compose.yml
- deployment/docker/requirements.txt
- deployment/minio/entrypoint.sh
- django_project/core/settings/base.py
- django_project/core/settings/dev.py
- django_project/core/settings/project.py
- django_project/core/settings/test.py
This fix https://github.com/kartoza/GeoHosting/issues/46
> Add minio for media storage

- django_project/core/settings/base.py
- django_project/core/settings/prod.py
- django_project/geohosting/resend_email_backend.py
> Add resend backend

- django_project/core/api.py
- django_project/core/tests/test_api.py
- django_project/core/urls.py
- django_project/geohosting/resend_email_backend.py
- django_project/geohosting/src/pages/CheckoutPage/Stripe.tsx
- django_project/geohosting/templates/home.html
- django_project/geohosting/urls.py
This will fix https://github.com/kartoza/GeoHosting/issues/70
> Update checkout to get key on API

- django_project/geohosting/src/redux/reducers/authSlice.ts
This email variable will be used when the user creates an issue on support
> patch: save user email on login

- django_project/geohosting/src/components/ImageWithSkeleton/ImageWithSkeleton.tsx
- django_project/geohosting/src/components/ProductCard/ProductCard.tsx
- django_project/geohosting/src/components/ProductOverview/ProductOverview.tsx
> Add skeleton loader for images

- django_project/geohosting/src/components/SupportTicketForm/SupportTicketForm.tsx
- django_project/geohosting/src/pages/DashboardPage/Support/SupportPage.tsx
- django_project/geohosting/src/redux/reducers/supportSlice.ts
- django_project/geohosting/tests/test_support.py
- django_project/geohosting/urls.py
- django_project/geohosting/views/auth.py
- django_project/geohosting/views/support.py
TODO:
- edit ticket is not implemented
- add pagination
- add search bar and filters
DONE:
- fetching user created tickets
> List support data on support page

- django_project/geohosting/src/components/LoginForm/LoginForm.tsx
> patch: remove the gray color on the show password button

- django_project/geohosting/src/components/Footer/Footer.tsx
- django_project/geohosting/src/components/LoginForm/LoginForm.tsx
- django_project/geohosting/src/components/ProductFeatureGrid/ProductFeatureGrid.tsx
- django_project/geohosting/src/components/ProductOverview/ProductOverview.tsx
- django_project/geohosting/src/components/ProductSupportGrid/ProductSupportGrid.tsx
- django_project/geohosting/src/pages/OverviewPage/OverviewPage.tsx
> Improve overview page

- django_project/geohosting/serializer/product.py
This should return 
metadata for product to frontend including things like github link which I will then link to the github button for product
> patch: return product meta

- django_project/geohosting/src/components/ProductCard/ProductCard.tsx
- django_project/geohosting/src/components/ProductPricing/ProductPricing.tsx
Description
the cards with coming soon badge will show visually that they're disabled and the mouse cursor is adjusted on hover
> patch: make coming soon unclickable

- django_project/geohosting/src/components/Footer/Footer.tsx
- django_project/geohosting/src/components/ProductOverview/ProductOverview.tsx
- django_project/geohosting/src/components/ProductSupportGrid/ProductSupportGrid.tsx
- django_project/geohosting/src/pages/OverviewPage/OverviewPage.tsx
- django_project/geohosting/src/theme/theme.ts
> Standardize website styling

- django_project/geohosting/src/components/DashboardSidePanel/DashboardSidePanel.tsx
Have update the highlight to look more like figma design
> patch: update sidebar highlight styles

- django_project/geohosting/api/product.py
- django_project/geohosting/serializer/product.py
- django_project/geohosting/src/components/ProductPricing/ProductPricing.tsx
- django_project/geohosting/src/redux/reducers/productsSlice.ts
- django_project/geohosting/src/utils/helpers.ts
- django_project/geohosting/src/utils/utils.ts
- django_project/geohosting/tests/test_product.py
Description
The user will be prompted to allow access to location so product price and currency can be adjusted according to users location
Adjustments:
- fetch user location
- send currency to back-end
- using currency from fronted fetch the appropriate values from db
> patch: update currency based on location

- django_project/geohosting/api/instance.py
- django_project/geohosting/forms/activity/create_instance.py
- django_project/geohosting/serializer/instance.py
- django_project/geohosting/src/pages/DashboardPage/DashboardMainPage.tsx
- django_project/geohosting/src/pages/DashboardPage/ServicesPage.tsx
- django_project/geohosting/src/redux/reducers/instanceSlice.ts
- django_project/geohosting/src/redux/store.ts
- django_project/geohosting/tests/test_instance.py
- django_project/geohosting/tests/test_sales_order.py
- django_project/geohosting/urls.py
this is linked to https://github.com/kartoza/GeoHosting/issues/133
> Add services page

- django_project/geohosting/models/product.py
- django_project/geohosting/tests/test_product.py
this linked to https://github.com/kartoza/GeoHosting/issues/71
> Delete old image

- django_project/core/settings/dev.py
- django_project/geohosting/api/instance.py
- django_project/geohosting/models/instance.py
- django_project/geohosting/src/pages/CheckoutPage/utils.tsx
- django_project/geohosting/src/pages/DashboardPage/Services/ServiceList.tsx
- django_project/geohosting/templates/emails/GeoHosting_Product is Ready.html
- django_project/geohosting/views/products.py
This fix https://github.com/kartoza/GeoHosting/issues/199
> Add fetching credential of instance

- docs/src/help_guide.md
> Initialize the help guide

- docs/src/help_guide.md
> Initialize the help_guide.md

- django_project/geohosting/templates/emails/GeoHosting_Product is Ready.html
@meomancer Please review styling changes made to the Product is Ready email notification
> Update GeoHosting_Product is Ready.html

- django_project/geohosting/templates/emails/GeoHosting_System Maintenance OR Issue Notification.html
@meomancer Please review changes made to the System maintenance/Issue notification email template.
> Update GeoHosting_System Maintenance OR Issue Notification.html

- django_project/geohosting/templates/emails/GeoHosting_Support Ticket Number_for user.html
@meomancer Please review these changes for the Support Ticket Number notification email.
> Update GeoHosting_Support Ticket Number_for user.html

- django_project/geohosting/templates/emails/GeoHosting_Support Ticket Closed_for user.html
@meomancer Please review and test the changes for the Support ticket closed notification
> Update GeoHosting_Support Ticket Closed_for user.html

- django_project/documentations/Service Level Agreement (SLA).md
- django_project/documentations/Service_Level_Agreement_(SLA)_Lda.md
- django_project/documentations/Service_Level_Agreement_(SLA)_Pty.md
Update to the SLA agreements to now include acceptable use policy (AUP) as well as client information in table
> Updates to SLA agreements 
